global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3001']

  - job_name: 'blackbox_http'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Choose which module to use

    static_configs:
      - targets:
          - http://backend:3001   # Internal app
          - https://example.com   # External website
          - http://frontend:3000  # Internal frontend

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115  # Blackbox exporter service
